#!/bin/bash

# If the tmp folder doesn't exist, create it as a symlink to a random folder in /tmp
if [ ! -d "tmp" ]; then
    ln -s "$(mktemp -d --suffix=dcssllm)" tmp
fi

uv run dcssllm/main.py 2>tmp/stderr.log

