/**
 * IMPORTANT: DO NOT EDIT THIS FILE IN THE crawl/ REPO.
 * EDIT THE VERSION IN THE crawl-patches DIRECTORY INSTEAD.
 * 
 * CHANGES TO THIS FILE IN THE crawl/ REPO WILL BE OVERWRITTEN.
 */

/**
 * @file
 * @brief Functions used to print game info for consumption by an LLM.
**/

#pragma once

void output_data_for_llm();
